/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AddCcat {
    }
    interface AddCurr {
    }
    interface AddEmpcat {
    }
    interface AddEmpgrp {
    }
    interface AddGrp {
    }
    interface AddItem {
    }
    interface AddScen {
    }
    interface AddStkcat {
    }
    interface AddStkgrp {
    }
    interface AddTariff {
    }
    interface AddUom {
    }
    interface AddUser {
    }
    interface AdditemGrp {
    }
    interface BuisAcc {
    }
    interface CostCate {
        "cccd": string;
    }
    interface CreateCamp {
    }
    interface CreateCase {
    }
    interface CreateContact {
        "a3": string;
    }
    interface CreateCust {
        "a4": string;
    }
    interface CreateLead {
    }
    interface CreateOppo {
    }
    interface CreatePara {
    }
    interface CreatePote {
    }
    interface CreateProCust {
        "a4": string;
    }
    interface CreateTemp {
        "a5": string;
    }
    interface CreateUser {
    }
    interface GenMailer {
        "a5": string;
    }
    interface GetAccount {
        "cccd": string;
    }
    interface GetActivities {
        "cccd": string;
    }
    interface GetAttendance {
        "cccd": string;
    }
    interface GetBudget {
        "cccd": string;
    }
    interface GetCampaign {
        "cccd": string;
    }
    interface GetCases {
        "cccd": string;
    }
    interface GetCcentre {
        "cccd": string;
    }
    interface GetContact {
        "cccd": string;
    }
    interface GetContra {
    }
    interface GetCurrencies {
        "cccd": string;
    }
    interface GetDaybook {
    }
    interface GetEmp {
        "cccd": string;
    }
    interface GetEmpcat {
        "cccd": string;
    }
    interface GetEmpgrp {
        "cccd": string;
    }
    interface GetGodown {
        "cccd": string;
    }
    interface GetGroup {
        "cccd": string;
    }
    interface GetJournalvoucher {
    }
    interface GetLead {
        "cccd": string;
    }
    interface GetLedger {
        "cccd": string;
    }
    interface GetMaterialout {
    }
    interface GetOpportunity {
        "cccd": string;
    }
    interface GetPayheads {
        "cccd": string;
    }
    interface GetPayment {
    }
    interface GetPayroll {
    }
    interface GetPemail {
        "cccd": string;
    }
    interface GetPlstkcat {
        "cccd": string;
    }
    interface GetPlstkgrp {
        "cccd": string;
    }
    interface GetPotential {
        "cccd": string;
    }
    interface GetProduct {
        "cccd": string;
    }
    interface GetPurchase {
    }
    interface GetPurchaseorder {
    }
    interface GetReceipt {
    }
    interface GetSales {
    }
    interface GetSalesorder {
    }
    interface GetScenario {
        "cccd": string;
    }
    interface GetSinglepayslip {
    }
    interface GetStockcate {
        "cccd": string;
    }
    interface GetStockgroup {
        "cccd": string;
    }
    interface GetStockitem {
        "cccd": string;
    }
    interface GetStockjournal {
    }
    interface GetTariff {
        "cccd": string;
    }
    interface GetUnits {
        "cccd": string;
    }
    interface GetUnitw {
        "cccd": string;
    }
    interface GetVoucher {
        "cccd": string;
    }
    interface ImpAct {
        "Name": string;
    }
    interface ImpCamp {
        "Name": string;
    }
    interface ImpCase {
        "Name": string;
    }
    interface ImpContact {
        "Name": string;
    }
    interface ImpLead {
        "Name": string;
    }
    interface ImpOppo {
        "Name": string;
    }
    interface ImpPote {
        "Name": string;
    }
    interface ImpProCust {
        "Name": string;
    }
    interface MyComponent {
        "atfile": string;
        "budfile": string;
        "cccd": string;
        "ccentfile": string;
        "ccfile": string;
        "cfile": string;
        "crfile": string;
        "ctfile": string;
        "dbfile": string;
        "ecatfile": string;
        "edfile": string;
        "efile": string;
        "egfile": string;
        "gfile": string;
        "gofile": string;
        "img": string;
        "jrfile": string;
        "lfile": string;
        "mainfile": string;
        "mofile": string;
        "msjfile": string;
        "payfile": string;
        "pfile": string;
        "plstcatfile": string;
        "plstkfile": string;
        "pofile": string;
        "prfile": string;
        "ptfile": string;
        "rtfile": string;
        "scfile": string;
        "sfile": string;
        "sgfile": string;
        "sifile": string;
        "sjfile": string;
        "slfile": string;
        "sofile": string;
        "spfile": string;
        "tfile": string;
        "ufile": string;
        "umfile": string;
        "user": string;
        "userfile": string;
        "vfile": string;
    }
    interface MyCrm {
        "acc": string;
        "aig": string;
        "asc": string;
        "ase": string;
        "ast": string;
        "ba": string;
        "c": string;
        "ca": string;
        "camp": string;
        "cc": string;
        "cca": string;
        "ccamp": string;
        "cccd": string;
        "ccust": string;
        "clead": string;
        "co": string;
        "copp": string;
        "cpc": string;
        "cpo": string;
        "ctemp": string;
        "cu": string;
        "erp": string;
        "ga": string;
        "gm": string;
        "ia": string;
        "ic": string;
        "ica": string;
        "icamp": string;
        "ilead": string;
        "iopp": string;
        "ipc": string;
        "ipo": string;
        "ipr": string;
        "lead": string;
        "logo": string;
        "opp": string;
        "po": string;
        "pr": string;
        "pro": string;
        "s": string;
        "soc": string;
        "user": string;
    }
    interface MySubnav {
        "create": string;
        "list": string;
    }
    interface PLogin {
        "logo": string;
        "nav": string;
        "user": string;
    }
    interface ScheduleCall {
    }
    interface ScheduleEvent {
    }
    interface ScheduleTask {
    }
    interface SocialNetwork {
        "image": string;
        "image1": string;
        "image2": string;
        "image3": string;
    }
    interface SuppLier {
        "a4": string;
    }
    interface WelCome {
        "img": string;
    }
}
declare global {
    interface HTMLAddCcatElement extends Components.AddCcat, HTMLStencilElement {
    }
    var HTMLAddCcatElement: {
        prototype: HTMLAddCcatElement;
        new (): HTMLAddCcatElement;
    };
    interface HTMLAddCurrElement extends Components.AddCurr, HTMLStencilElement {
    }
    var HTMLAddCurrElement: {
        prototype: HTMLAddCurrElement;
        new (): HTMLAddCurrElement;
    };
    interface HTMLAddEmpcatElement extends Components.AddEmpcat, HTMLStencilElement {
    }
    var HTMLAddEmpcatElement: {
        prototype: HTMLAddEmpcatElement;
        new (): HTMLAddEmpcatElement;
    };
    interface HTMLAddEmpgrpElement extends Components.AddEmpgrp, HTMLStencilElement {
    }
    var HTMLAddEmpgrpElement: {
        prototype: HTMLAddEmpgrpElement;
        new (): HTMLAddEmpgrpElement;
    };
    interface HTMLAddGrpElement extends Components.AddGrp, HTMLStencilElement {
    }
    var HTMLAddGrpElement: {
        prototype: HTMLAddGrpElement;
        new (): HTMLAddGrpElement;
    };
    interface HTMLAddItemElement extends Components.AddItem, HTMLStencilElement {
    }
    var HTMLAddItemElement: {
        prototype: HTMLAddItemElement;
        new (): HTMLAddItemElement;
    };
    interface HTMLAddScenElement extends Components.AddScen, HTMLStencilElement {
    }
    var HTMLAddScenElement: {
        prototype: HTMLAddScenElement;
        new (): HTMLAddScenElement;
    };
    interface HTMLAddStkcatElement extends Components.AddStkcat, HTMLStencilElement {
    }
    var HTMLAddStkcatElement: {
        prototype: HTMLAddStkcatElement;
        new (): HTMLAddStkcatElement;
    };
    interface HTMLAddStkgrpElement extends Components.AddStkgrp, HTMLStencilElement {
    }
    var HTMLAddStkgrpElement: {
        prototype: HTMLAddStkgrpElement;
        new (): HTMLAddStkgrpElement;
    };
    interface HTMLAddTariffElement extends Components.AddTariff, HTMLStencilElement {
    }
    var HTMLAddTariffElement: {
        prototype: HTMLAddTariffElement;
        new (): HTMLAddTariffElement;
    };
    interface HTMLAddUomElement extends Components.AddUom, HTMLStencilElement {
    }
    var HTMLAddUomElement: {
        prototype: HTMLAddUomElement;
        new (): HTMLAddUomElement;
    };
    interface HTMLAddUserElement extends Components.AddUser, HTMLStencilElement {
    }
    var HTMLAddUserElement: {
        prototype: HTMLAddUserElement;
        new (): HTMLAddUserElement;
    };
    interface HTMLAdditemGrpElement extends Components.AdditemGrp, HTMLStencilElement {
    }
    var HTMLAdditemGrpElement: {
        prototype: HTMLAdditemGrpElement;
        new (): HTMLAdditemGrpElement;
    };
    interface HTMLBuisAccElement extends Components.BuisAcc, HTMLStencilElement {
    }
    var HTMLBuisAccElement: {
        prototype: HTMLBuisAccElement;
        new (): HTMLBuisAccElement;
    };
    interface HTMLCostCateElement extends Components.CostCate, HTMLStencilElement {
    }
    var HTMLCostCateElement: {
        prototype: HTMLCostCateElement;
        new (): HTMLCostCateElement;
    };
    interface HTMLCreateCampElement extends Components.CreateCamp, HTMLStencilElement {
    }
    var HTMLCreateCampElement: {
        prototype: HTMLCreateCampElement;
        new (): HTMLCreateCampElement;
    };
    interface HTMLCreateCaseElement extends Components.CreateCase, HTMLStencilElement {
    }
    var HTMLCreateCaseElement: {
        prototype: HTMLCreateCaseElement;
        new (): HTMLCreateCaseElement;
    };
    interface HTMLCreateContactElement extends Components.CreateContact, HTMLStencilElement {
    }
    var HTMLCreateContactElement: {
        prototype: HTMLCreateContactElement;
        new (): HTMLCreateContactElement;
    };
    interface HTMLCreateCustElement extends Components.CreateCust, HTMLStencilElement {
    }
    var HTMLCreateCustElement: {
        prototype: HTMLCreateCustElement;
        new (): HTMLCreateCustElement;
    };
    interface HTMLCreateLeadElement extends Components.CreateLead, HTMLStencilElement {
    }
    var HTMLCreateLeadElement: {
        prototype: HTMLCreateLeadElement;
        new (): HTMLCreateLeadElement;
    };
    interface HTMLCreateOppoElement extends Components.CreateOppo, HTMLStencilElement {
    }
    var HTMLCreateOppoElement: {
        prototype: HTMLCreateOppoElement;
        new (): HTMLCreateOppoElement;
    };
    interface HTMLCreateParaElement extends Components.CreatePara, HTMLStencilElement {
    }
    var HTMLCreateParaElement: {
        prototype: HTMLCreateParaElement;
        new (): HTMLCreateParaElement;
    };
    interface HTMLCreatePoteElement extends Components.CreatePote, HTMLStencilElement {
    }
    var HTMLCreatePoteElement: {
        prototype: HTMLCreatePoteElement;
        new (): HTMLCreatePoteElement;
    };
    interface HTMLCreateProCustElement extends Components.CreateProCust, HTMLStencilElement {
    }
    var HTMLCreateProCustElement: {
        prototype: HTMLCreateProCustElement;
        new (): HTMLCreateProCustElement;
    };
    interface HTMLCreateTempElement extends Components.CreateTemp, HTMLStencilElement {
    }
    var HTMLCreateTempElement: {
        prototype: HTMLCreateTempElement;
        new (): HTMLCreateTempElement;
    };
    interface HTMLCreateUserElement extends Components.CreateUser, HTMLStencilElement {
    }
    var HTMLCreateUserElement: {
        prototype: HTMLCreateUserElement;
        new (): HTMLCreateUserElement;
    };
    interface HTMLGenMailerElement extends Components.GenMailer, HTMLStencilElement {
    }
    var HTMLGenMailerElement: {
        prototype: HTMLGenMailerElement;
        new (): HTMLGenMailerElement;
    };
    interface HTMLGetAccountElement extends Components.GetAccount, HTMLStencilElement {
    }
    var HTMLGetAccountElement: {
        prototype: HTMLGetAccountElement;
        new (): HTMLGetAccountElement;
    };
    interface HTMLGetActivitiesElement extends Components.GetActivities, HTMLStencilElement {
    }
    var HTMLGetActivitiesElement: {
        prototype: HTMLGetActivitiesElement;
        new (): HTMLGetActivitiesElement;
    };
    interface HTMLGetAttendanceElement extends Components.GetAttendance, HTMLStencilElement {
    }
    var HTMLGetAttendanceElement: {
        prototype: HTMLGetAttendanceElement;
        new (): HTMLGetAttendanceElement;
    };
    interface HTMLGetBudgetElement extends Components.GetBudget, HTMLStencilElement {
    }
    var HTMLGetBudgetElement: {
        prototype: HTMLGetBudgetElement;
        new (): HTMLGetBudgetElement;
    };
    interface HTMLGetCampaignElement extends Components.GetCampaign, HTMLStencilElement {
    }
    var HTMLGetCampaignElement: {
        prototype: HTMLGetCampaignElement;
        new (): HTMLGetCampaignElement;
    };
    interface HTMLGetCasesElement extends Components.GetCases, HTMLStencilElement {
    }
    var HTMLGetCasesElement: {
        prototype: HTMLGetCasesElement;
        new (): HTMLGetCasesElement;
    };
    interface HTMLGetCcentreElement extends Components.GetCcentre, HTMLStencilElement {
    }
    var HTMLGetCcentreElement: {
        prototype: HTMLGetCcentreElement;
        new (): HTMLGetCcentreElement;
    };
    interface HTMLGetContactElement extends Components.GetContact, HTMLStencilElement {
    }
    var HTMLGetContactElement: {
        prototype: HTMLGetContactElement;
        new (): HTMLGetContactElement;
    };
    interface HTMLGetContraElement extends Components.GetContra, HTMLStencilElement {
    }
    var HTMLGetContraElement: {
        prototype: HTMLGetContraElement;
        new (): HTMLGetContraElement;
    };
    interface HTMLGetCurrenciesElement extends Components.GetCurrencies, HTMLStencilElement {
    }
    var HTMLGetCurrenciesElement: {
        prototype: HTMLGetCurrenciesElement;
        new (): HTMLGetCurrenciesElement;
    };
    interface HTMLGetDaybookElement extends Components.GetDaybook, HTMLStencilElement {
    }
    var HTMLGetDaybookElement: {
        prototype: HTMLGetDaybookElement;
        new (): HTMLGetDaybookElement;
    };
    interface HTMLGetEmpElement extends Components.GetEmp, HTMLStencilElement {
    }
    var HTMLGetEmpElement: {
        prototype: HTMLGetEmpElement;
        new (): HTMLGetEmpElement;
    };
    interface HTMLGetEmpcatElement extends Components.GetEmpcat, HTMLStencilElement {
    }
    var HTMLGetEmpcatElement: {
        prototype: HTMLGetEmpcatElement;
        new (): HTMLGetEmpcatElement;
    };
    interface HTMLGetEmpgrpElement extends Components.GetEmpgrp, HTMLStencilElement {
    }
    var HTMLGetEmpgrpElement: {
        prototype: HTMLGetEmpgrpElement;
        new (): HTMLGetEmpgrpElement;
    };
    interface HTMLGetGodownElement extends Components.GetGodown, HTMLStencilElement {
    }
    var HTMLGetGodownElement: {
        prototype: HTMLGetGodownElement;
        new (): HTMLGetGodownElement;
    };
    interface HTMLGetGroupElement extends Components.GetGroup, HTMLStencilElement {
    }
    var HTMLGetGroupElement: {
        prototype: HTMLGetGroupElement;
        new (): HTMLGetGroupElement;
    };
    interface HTMLGetJournalvoucherElement extends Components.GetJournalvoucher, HTMLStencilElement {
    }
    var HTMLGetJournalvoucherElement: {
        prototype: HTMLGetJournalvoucherElement;
        new (): HTMLGetJournalvoucherElement;
    };
    interface HTMLGetLeadElement extends Components.GetLead, HTMLStencilElement {
    }
    var HTMLGetLeadElement: {
        prototype: HTMLGetLeadElement;
        new (): HTMLGetLeadElement;
    };
    interface HTMLGetLedgerElement extends Components.GetLedger, HTMLStencilElement {
    }
    var HTMLGetLedgerElement: {
        prototype: HTMLGetLedgerElement;
        new (): HTMLGetLedgerElement;
    };
    interface HTMLGetMaterialoutElement extends Components.GetMaterialout, HTMLStencilElement {
    }
    var HTMLGetMaterialoutElement: {
        prototype: HTMLGetMaterialoutElement;
        new (): HTMLGetMaterialoutElement;
    };
    interface HTMLGetOpportunityElement extends Components.GetOpportunity, HTMLStencilElement {
    }
    var HTMLGetOpportunityElement: {
        prototype: HTMLGetOpportunityElement;
        new (): HTMLGetOpportunityElement;
    };
    interface HTMLGetPayheadsElement extends Components.GetPayheads, HTMLStencilElement {
    }
    var HTMLGetPayheadsElement: {
        prototype: HTMLGetPayheadsElement;
        new (): HTMLGetPayheadsElement;
    };
    interface HTMLGetPaymentElement extends Components.GetPayment, HTMLStencilElement {
    }
    var HTMLGetPaymentElement: {
        prototype: HTMLGetPaymentElement;
        new (): HTMLGetPaymentElement;
    };
    interface HTMLGetPayrollElement extends Components.GetPayroll, HTMLStencilElement {
    }
    var HTMLGetPayrollElement: {
        prototype: HTMLGetPayrollElement;
        new (): HTMLGetPayrollElement;
    };
    interface HTMLGetPemailElement extends Components.GetPemail, HTMLStencilElement {
    }
    var HTMLGetPemailElement: {
        prototype: HTMLGetPemailElement;
        new (): HTMLGetPemailElement;
    };
    interface HTMLGetPlstkcatElement extends Components.GetPlstkcat, HTMLStencilElement {
    }
    var HTMLGetPlstkcatElement: {
        prototype: HTMLGetPlstkcatElement;
        new (): HTMLGetPlstkcatElement;
    };
    interface HTMLGetPlstkgrpElement extends Components.GetPlstkgrp, HTMLStencilElement {
    }
    var HTMLGetPlstkgrpElement: {
        prototype: HTMLGetPlstkgrpElement;
        new (): HTMLGetPlstkgrpElement;
    };
    interface HTMLGetPotentialElement extends Components.GetPotential, HTMLStencilElement {
    }
    var HTMLGetPotentialElement: {
        prototype: HTMLGetPotentialElement;
        new (): HTMLGetPotentialElement;
    };
    interface HTMLGetProductElement extends Components.GetProduct, HTMLStencilElement {
    }
    var HTMLGetProductElement: {
        prototype: HTMLGetProductElement;
        new (): HTMLGetProductElement;
    };
    interface HTMLGetPurchaseElement extends Components.GetPurchase, HTMLStencilElement {
    }
    var HTMLGetPurchaseElement: {
        prototype: HTMLGetPurchaseElement;
        new (): HTMLGetPurchaseElement;
    };
    interface HTMLGetPurchaseorderElement extends Components.GetPurchaseorder, HTMLStencilElement {
    }
    var HTMLGetPurchaseorderElement: {
        prototype: HTMLGetPurchaseorderElement;
        new (): HTMLGetPurchaseorderElement;
    };
    interface HTMLGetReceiptElement extends Components.GetReceipt, HTMLStencilElement {
    }
    var HTMLGetReceiptElement: {
        prototype: HTMLGetReceiptElement;
        new (): HTMLGetReceiptElement;
    };
    interface HTMLGetSalesElement extends Components.GetSales, HTMLStencilElement {
    }
    var HTMLGetSalesElement: {
        prototype: HTMLGetSalesElement;
        new (): HTMLGetSalesElement;
    };
    interface HTMLGetSalesorderElement extends Components.GetSalesorder, HTMLStencilElement {
    }
    var HTMLGetSalesorderElement: {
        prototype: HTMLGetSalesorderElement;
        new (): HTMLGetSalesorderElement;
    };
    interface HTMLGetScenarioElement extends Components.GetScenario, HTMLStencilElement {
    }
    var HTMLGetScenarioElement: {
        prototype: HTMLGetScenarioElement;
        new (): HTMLGetScenarioElement;
    };
    interface HTMLGetSinglepayslipElement extends Components.GetSinglepayslip, HTMLStencilElement {
    }
    var HTMLGetSinglepayslipElement: {
        prototype: HTMLGetSinglepayslipElement;
        new (): HTMLGetSinglepayslipElement;
    };
    interface HTMLGetStockcateElement extends Components.GetStockcate, HTMLStencilElement {
    }
    var HTMLGetStockcateElement: {
        prototype: HTMLGetStockcateElement;
        new (): HTMLGetStockcateElement;
    };
    interface HTMLGetStockgroupElement extends Components.GetStockgroup, HTMLStencilElement {
    }
    var HTMLGetStockgroupElement: {
        prototype: HTMLGetStockgroupElement;
        new (): HTMLGetStockgroupElement;
    };
    interface HTMLGetStockitemElement extends Components.GetStockitem, HTMLStencilElement {
    }
    var HTMLGetStockitemElement: {
        prototype: HTMLGetStockitemElement;
        new (): HTMLGetStockitemElement;
    };
    interface HTMLGetStockjournalElement extends Components.GetStockjournal, HTMLStencilElement {
    }
    var HTMLGetStockjournalElement: {
        prototype: HTMLGetStockjournalElement;
        new (): HTMLGetStockjournalElement;
    };
    interface HTMLGetTariffElement extends Components.GetTariff, HTMLStencilElement {
    }
    var HTMLGetTariffElement: {
        prototype: HTMLGetTariffElement;
        new (): HTMLGetTariffElement;
    };
    interface HTMLGetUnitsElement extends Components.GetUnits, HTMLStencilElement {
    }
    var HTMLGetUnitsElement: {
        prototype: HTMLGetUnitsElement;
        new (): HTMLGetUnitsElement;
    };
    interface HTMLGetUnitwElement extends Components.GetUnitw, HTMLStencilElement {
    }
    var HTMLGetUnitwElement: {
        prototype: HTMLGetUnitwElement;
        new (): HTMLGetUnitwElement;
    };
    interface HTMLGetVoucherElement extends Components.GetVoucher, HTMLStencilElement {
    }
    var HTMLGetVoucherElement: {
        prototype: HTMLGetVoucherElement;
        new (): HTMLGetVoucherElement;
    };
    interface HTMLImpActElement extends Components.ImpAct, HTMLStencilElement {
    }
    var HTMLImpActElement: {
        prototype: HTMLImpActElement;
        new (): HTMLImpActElement;
    };
    interface HTMLImpCampElement extends Components.ImpCamp, HTMLStencilElement {
    }
    var HTMLImpCampElement: {
        prototype: HTMLImpCampElement;
        new (): HTMLImpCampElement;
    };
    interface HTMLImpCaseElement extends Components.ImpCase, HTMLStencilElement {
    }
    var HTMLImpCaseElement: {
        prototype: HTMLImpCaseElement;
        new (): HTMLImpCaseElement;
    };
    interface HTMLImpContactElement extends Components.ImpContact, HTMLStencilElement {
    }
    var HTMLImpContactElement: {
        prototype: HTMLImpContactElement;
        new (): HTMLImpContactElement;
    };
    interface HTMLImpLeadElement extends Components.ImpLead, HTMLStencilElement {
    }
    var HTMLImpLeadElement: {
        prototype: HTMLImpLeadElement;
        new (): HTMLImpLeadElement;
    };
    interface HTMLImpOppoElement extends Components.ImpOppo, HTMLStencilElement {
    }
    var HTMLImpOppoElement: {
        prototype: HTMLImpOppoElement;
        new (): HTMLImpOppoElement;
    };
    interface HTMLImpPoteElement extends Components.ImpPote, HTMLStencilElement {
    }
    var HTMLImpPoteElement: {
        prototype: HTMLImpPoteElement;
        new (): HTMLImpPoteElement;
    };
    interface HTMLImpProCustElement extends Components.ImpProCust, HTMLStencilElement {
    }
    var HTMLImpProCustElement: {
        prototype: HTMLImpProCustElement;
        new (): HTMLImpProCustElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyCrmElement extends Components.MyCrm, HTMLStencilElement {
    }
    var HTMLMyCrmElement: {
        prototype: HTMLMyCrmElement;
        new (): HTMLMyCrmElement;
    };
    interface HTMLMySubnavElement extends Components.MySubnav, HTMLStencilElement {
    }
    var HTMLMySubnavElement: {
        prototype: HTMLMySubnavElement;
        new (): HTMLMySubnavElement;
    };
    interface HTMLPLoginElement extends Components.PLogin, HTMLStencilElement {
    }
    var HTMLPLoginElement: {
        prototype: HTMLPLoginElement;
        new (): HTMLPLoginElement;
    };
    interface HTMLScheduleCallElement extends Components.ScheduleCall, HTMLStencilElement {
    }
    var HTMLScheduleCallElement: {
        prototype: HTMLScheduleCallElement;
        new (): HTMLScheduleCallElement;
    };
    interface HTMLScheduleEventElement extends Components.ScheduleEvent, HTMLStencilElement {
    }
    var HTMLScheduleEventElement: {
        prototype: HTMLScheduleEventElement;
        new (): HTMLScheduleEventElement;
    };
    interface HTMLScheduleTaskElement extends Components.ScheduleTask, HTMLStencilElement {
    }
    var HTMLScheduleTaskElement: {
        prototype: HTMLScheduleTaskElement;
        new (): HTMLScheduleTaskElement;
    };
    interface HTMLSocialNetworkElement extends Components.SocialNetwork, HTMLStencilElement {
    }
    var HTMLSocialNetworkElement: {
        prototype: HTMLSocialNetworkElement;
        new (): HTMLSocialNetworkElement;
    };
    interface HTMLSuppLierElement extends Components.SuppLier, HTMLStencilElement {
    }
    var HTMLSuppLierElement: {
        prototype: HTMLSuppLierElement;
        new (): HTMLSuppLierElement;
    };
    interface HTMLWelComeElement extends Components.WelCome, HTMLStencilElement {
    }
    var HTMLWelComeElement: {
        prototype: HTMLWelComeElement;
        new (): HTMLWelComeElement;
    };
    interface HTMLElementTagNameMap {
        "add-ccat": HTMLAddCcatElement;
        "add-curr": HTMLAddCurrElement;
        "add-empcat": HTMLAddEmpcatElement;
        "add-empgrp": HTMLAddEmpgrpElement;
        "add-grp": HTMLAddGrpElement;
        "add-item": HTMLAddItemElement;
        "add-scen": HTMLAddScenElement;
        "add-stkcat": HTMLAddStkcatElement;
        "add-stkgrp": HTMLAddStkgrpElement;
        "add-tariff": HTMLAddTariffElement;
        "add-uom": HTMLAddUomElement;
        "add-user": HTMLAddUserElement;
        "additem-grp": HTMLAdditemGrpElement;
        "buis-acc": HTMLBuisAccElement;
        "cost-cate": HTMLCostCateElement;
        "create-camp": HTMLCreateCampElement;
        "create-case": HTMLCreateCaseElement;
        "create-contact": HTMLCreateContactElement;
        "create-cust": HTMLCreateCustElement;
        "create-lead": HTMLCreateLeadElement;
        "create-oppo": HTMLCreateOppoElement;
        "create-para": HTMLCreateParaElement;
        "create-pote": HTMLCreatePoteElement;
        "create-pro-cust": HTMLCreateProCustElement;
        "create-temp": HTMLCreateTempElement;
        "create-user": HTMLCreateUserElement;
        "gen-mailer": HTMLGenMailerElement;
        "get-account": HTMLGetAccountElement;
        "get-activities": HTMLGetActivitiesElement;
        "get-attendance": HTMLGetAttendanceElement;
        "get-budget": HTMLGetBudgetElement;
        "get-campaign": HTMLGetCampaignElement;
        "get-cases": HTMLGetCasesElement;
        "get-ccentre": HTMLGetCcentreElement;
        "get-contact": HTMLGetContactElement;
        "get-contra": HTMLGetContraElement;
        "get-currencies": HTMLGetCurrenciesElement;
        "get-daybook": HTMLGetDaybookElement;
        "get-emp": HTMLGetEmpElement;
        "get-empcat": HTMLGetEmpcatElement;
        "get-empgrp": HTMLGetEmpgrpElement;
        "get-godown": HTMLGetGodownElement;
        "get-group": HTMLGetGroupElement;
        "get-journalvoucher": HTMLGetJournalvoucherElement;
        "get-lead": HTMLGetLeadElement;
        "get-ledger": HTMLGetLedgerElement;
        "get-materialout": HTMLGetMaterialoutElement;
        "get-opportunity": HTMLGetOpportunityElement;
        "get-payheads": HTMLGetPayheadsElement;
        "get-payment": HTMLGetPaymentElement;
        "get-payroll": HTMLGetPayrollElement;
        "get-pemail": HTMLGetPemailElement;
        "get-plstkcat": HTMLGetPlstkcatElement;
        "get-plstkgrp": HTMLGetPlstkgrpElement;
        "get-potential": HTMLGetPotentialElement;
        "get-product": HTMLGetProductElement;
        "get-purchase": HTMLGetPurchaseElement;
        "get-purchaseorder": HTMLGetPurchaseorderElement;
        "get-receipt": HTMLGetReceiptElement;
        "get-sales": HTMLGetSalesElement;
        "get-salesorder": HTMLGetSalesorderElement;
        "get-scenario": HTMLGetScenarioElement;
        "get-singlepayslip": HTMLGetSinglepayslipElement;
        "get-stockcate": HTMLGetStockcateElement;
        "get-stockgroup": HTMLGetStockgroupElement;
        "get-stockitem": HTMLGetStockitemElement;
        "get-stockjournal": HTMLGetStockjournalElement;
        "get-tariff": HTMLGetTariffElement;
        "get-units": HTMLGetUnitsElement;
        "get-unitw": HTMLGetUnitwElement;
        "get-voucher": HTMLGetVoucherElement;
        "imp-act": HTMLImpActElement;
        "imp-camp": HTMLImpCampElement;
        "imp-case": HTMLImpCaseElement;
        "imp-contact": HTMLImpContactElement;
        "imp-lead": HTMLImpLeadElement;
        "imp-oppo": HTMLImpOppoElement;
        "imp-pote": HTMLImpPoteElement;
        "imp-pro-cust": HTMLImpProCustElement;
        "my-component": HTMLMyComponentElement;
        "my-crm": HTMLMyCrmElement;
        "my-subnav": HTMLMySubnavElement;
        "p-login": HTMLPLoginElement;
        "schedule-call": HTMLScheduleCallElement;
        "schedule-event": HTMLScheduleEventElement;
        "schedule-task": HTMLScheduleTaskElement;
        "social-network": HTMLSocialNetworkElement;
        "supp-lier": HTMLSuppLierElement;
        "wel-come": HTMLWelComeElement;
    }
}
declare namespace LocalJSX {
    interface AddCcat {
    }
    interface AddCurr {
    }
    interface AddEmpcat {
    }
    interface AddEmpgrp {
    }
    interface AddGrp {
    }
    interface AddItem {
    }
    interface AddScen {
    }
    interface AddStkcat {
    }
    interface AddStkgrp {
    }
    interface AddTariff {
    }
    interface AddUom {
    }
    interface AddUser {
    }
    interface AdditemGrp {
    }
    interface BuisAcc {
    }
    interface CostCate {
        "cccd"?: string;
    }
    interface CreateCamp {
    }
    interface CreateCase {
    }
    interface CreateContact {
        "a3"?: string;
    }
    interface CreateCust {
        "a4"?: string;
    }
    interface CreateLead {
    }
    interface CreateOppo {
    }
    interface CreatePara {
    }
    interface CreatePote {
    }
    interface CreateProCust {
        "a4"?: string;
    }
    interface CreateTemp {
        "a5"?: string;
    }
    interface CreateUser {
    }
    interface GenMailer {
        "a5"?: string;
    }
    interface GetAccount {
        "cccd"?: string;
    }
    interface GetActivities {
        "cccd"?: string;
    }
    interface GetAttendance {
        "cccd"?: string;
    }
    interface GetBudget {
        "cccd"?: string;
    }
    interface GetCampaign {
        "cccd"?: string;
    }
    interface GetCases {
        "cccd"?: string;
    }
    interface GetCcentre {
        "cccd"?: string;
    }
    interface GetContact {
        "cccd"?: string;
    }
    interface GetContra {
    }
    interface GetCurrencies {
        "cccd"?: string;
    }
    interface GetDaybook {
    }
    interface GetEmp {
        "cccd"?: string;
    }
    interface GetEmpcat {
        "cccd"?: string;
    }
    interface GetEmpgrp {
        "cccd"?: string;
    }
    interface GetGodown {
        "cccd"?: string;
    }
    interface GetGroup {
        "cccd"?: string;
    }
    interface GetJournalvoucher {
    }
    interface GetLead {
        "cccd"?: string;
    }
    interface GetLedger {
        "cccd"?: string;
    }
    interface GetMaterialout {
    }
    interface GetOpportunity {
        "cccd"?: string;
    }
    interface GetPayheads {
        "cccd"?: string;
    }
    interface GetPayment {
    }
    interface GetPayroll {
    }
    interface GetPemail {
        "cccd"?: string;
    }
    interface GetPlstkcat {
        "cccd"?: string;
    }
    interface GetPlstkgrp {
        "cccd"?: string;
    }
    interface GetPotential {
        "cccd"?: string;
    }
    interface GetProduct {
        "cccd"?: string;
    }
    interface GetPurchase {
    }
    interface GetPurchaseorder {
    }
    interface GetReceipt {
    }
    interface GetSales {
    }
    interface GetSalesorder {
    }
    interface GetScenario {
        "cccd"?: string;
    }
    interface GetSinglepayslip {
    }
    interface GetStockcate {
        "cccd"?: string;
    }
    interface GetStockgroup {
        "cccd"?: string;
    }
    interface GetStockitem {
        "cccd"?: string;
    }
    interface GetStockjournal {
    }
    interface GetTariff {
        "cccd"?: string;
    }
    interface GetUnits {
        "cccd"?: string;
    }
    interface GetUnitw {
        "cccd"?: string;
    }
    interface GetVoucher {
        "cccd"?: string;
    }
    interface ImpAct {
        "Name"?: string;
    }
    interface ImpCamp {
        "Name"?: string;
    }
    interface ImpCase {
        "Name"?: string;
    }
    interface ImpContact {
        "Name"?: string;
    }
    interface ImpLead {
        "Name"?: string;
    }
    interface ImpOppo {
        "Name"?: string;
    }
    interface ImpPote {
        "Name"?: string;
    }
    interface ImpProCust {
        "Name"?: string;
    }
    interface MyComponent {
        "atfile"?: string;
        "budfile"?: string;
        "cccd"?: string;
        "ccentfile"?: string;
        "ccfile"?: string;
        "cfile"?: string;
        "crfile"?: string;
        "ctfile"?: string;
        "dbfile"?: string;
        "ecatfile"?: string;
        "edfile"?: string;
        "efile"?: string;
        "egfile"?: string;
        "gfile"?: string;
        "gofile"?: string;
        "img"?: string;
        "jrfile"?: string;
        "lfile"?: string;
        "mainfile"?: string;
        "mofile"?: string;
        "msjfile"?: string;
        "payfile"?: string;
        "pfile"?: string;
        "plstcatfile"?: string;
        "plstkfile"?: string;
        "pofile"?: string;
        "prfile"?: string;
        "ptfile"?: string;
        "rtfile"?: string;
        "scfile"?: string;
        "sfile"?: string;
        "sgfile"?: string;
        "sifile"?: string;
        "sjfile"?: string;
        "slfile"?: string;
        "sofile"?: string;
        "spfile"?: string;
        "tfile"?: string;
        "ufile"?: string;
        "umfile"?: string;
        "user"?: string;
        "userfile"?: string;
        "vfile"?: string;
    }
    interface MyCrm {
        "acc"?: string;
        "aig"?: string;
        "asc"?: string;
        "ase"?: string;
        "ast"?: string;
        "ba"?: string;
        "c"?: string;
        "ca"?: string;
        "camp"?: string;
        "cc"?: string;
        "cca"?: string;
        "ccamp"?: string;
        "cccd"?: string;
        "ccust"?: string;
        "clead"?: string;
        "co"?: string;
        "copp"?: string;
        "cpc"?: string;
        "cpo"?: string;
        "ctemp"?: string;
        "cu"?: string;
        "erp"?: string;
        "ga"?: string;
        "gm"?: string;
        "ia"?: string;
        "ic"?: string;
        "ica"?: string;
        "icamp"?: string;
        "ilead"?: string;
        "iopp"?: string;
        "ipc"?: string;
        "ipo"?: string;
        "ipr"?: string;
        "lead"?: string;
        "logo"?: string;
        "opp"?: string;
        "po"?: string;
        "pr"?: string;
        "pro"?: string;
        "s"?: string;
        "soc"?: string;
        "user"?: string;
    }
    interface MySubnav {
        "create"?: string;
        "list"?: string;
    }
    interface PLogin {
        "logo"?: string;
        "nav"?: string;
        "user"?: string;
    }
    interface ScheduleCall {
    }
    interface ScheduleEvent {
    }
    interface ScheduleTask {
    }
    interface SocialNetwork {
        "image"?: string;
        "image1"?: string;
        "image2"?: string;
        "image3"?: string;
    }
    interface SuppLier {
        "a4"?: string;
    }
    interface WelCome {
        "img"?: string;
    }
    interface IntrinsicElements {
        "add-ccat": AddCcat;
        "add-curr": AddCurr;
        "add-empcat": AddEmpcat;
        "add-empgrp": AddEmpgrp;
        "add-grp": AddGrp;
        "add-item": AddItem;
        "add-scen": AddScen;
        "add-stkcat": AddStkcat;
        "add-stkgrp": AddStkgrp;
        "add-tariff": AddTariff;
        "add-uom": AddUom;
        "add-user": AddUser;
        "additem-grp": AdditemGrp;
        "buis-acc": BuisAcc;
        "cost-cate": CostCate;
        "create-camp": CreateCamp;
        "create-case": CreateCase;
        "create-contact": CreateContact;
        "create-cust": CreateCust;
        "create-lead": CreateLead;
        "create-oppo": CreateOppo;
        "create-para": CreatePara;
        "create-pote": CreatePote;
        "create-pro-cust": CreateProCust;
        "create-temp": CreateTemp;
        "create-user": CreateUser;
        "gen-mailer": GenMailer;
        "get-account": GetAccount;
        "get-activities": GetActivities;
        "get-attendance": GetAttendance;
        "get-budget": GetBudget;
        "get-campaign": GetCampaign;
        "get-cases": GetCases;
        "get-ccentre": GetCcentre;
        "get-contact": GetContact;
        "get-contra": GetContra;
        "get-currencies": GetCurrencies;
        "get-daybook": GetDaybook;
        "get-emp": GetEmp;
        "get-empcat": GetEmpcat;
        "get-empgrp": GetEmpgrp;
        "get-godown": GetGodown;
        "get-group": GetGroup;
        "get-journalvoucher": GetJournalvoucher;
        "get-lead": GetLead;
        "get-ledger": GetLedger;
        "get-materialout": GetMaterialout;
        "get-opportunity": GetOpportunity;
        "get-payheads": GetPayheads;
        "get-payment": GetPayment;
        "get-payroll": GetPayroll;
        "get-pemail": GetPemail;
        "get-plstkcat": GetPlstkcat;
        "get-plstkgrp": GetPlstkgrp;
        "get-potential": GetPotential;
        "get-product": GetProduct;
        "get-purchase": GetPurchase;
        "get-purchaseorder": GetPurchaseorder;
        "get-receipt": GetReceipt;
        "get-sales": GetSales;
        "get-salesorder": GetSalesorder;
        "get-scenario": GetScenario;
        "get-singlepayslip": GetSinglepayslip;
        "get-stockcate": GetStockcate;
        "get-stockgroup": GetStockgroup;
        "get-stockitem": GetStockitem;
        "get-stockjournal": GetStockjournal;
        "get-tariff": GetTariff;
        "get-units": GetUnits;
        "get-unitw": GetUnitw;
        "get-voucher": GetVoucher;
        "imp-act": ImpAct;
        "imp-camp": ImpCamp;
        "imp-case": ImpCase;
        "imp-contact": ImpContact;
        "imp-lead": ImpLead;
        "imp-oppo": ImpOppo;
        "imp-pote": ImpPote;
        "imp-pro-cust": ImpProCust;
        "my-component": MyComponent;
        "my-crm": MyCrm;
        "my-subnav": MySubnav;
        "p-login": PLogin;
        "schedule-call": ScheduleCall;
        "schedule-event": ScheduleEvent;
        "schedule-task": ScheduleTask;
        "social-network": SocialNetwork;
        "supp-lier": SuppLier;
        "wel-come": WelCome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-ccat": LocalJSX.AddCcat & JSXBase.HTMLAttributes<HTMLAddCcatElement>;
            "add-curr": LocalJSX.AddCurr & JSXBase.HTMLAttributes<HTMLAddCurrElement>;
            "add-empcat": LocalJSX.AddEmpcat & JSXBase.HTMLAttributes<HTMLAddEmpcatElement>;
            "add-empgrp": LocalJSX.AddEmpgrp & JSXBase.HTMLAttributes<HTMLAddEmpgrpElement>;
            "add-grp": LocalJSX.AddGrp & JSXBase.HTMLAttributes<HTMLAddGrpElement>;
            "add-item": LocalJSX.AddItem & JSXBase.HTMLAttributes<HTMLAddItemElement>;
            "add-scen": LocalJSX.AddScen & JSXBase.HTMLAttributes<HTMLAddScenElement>;
            "add-stkcat": LocalJSX.AddStkcat & JSXBase.HTMLAttributes<HTMLAddStkcatElement>;
            "add-stkgrp": LocalJSX.AddStkgrp & JSXBase.HTMLAttributes<HTMLAddStkgrpElement>;
            "add-tariff": LocalJSX.AddTariff & JSXBase.HTMLAttributes<HTMLAddTariffElement>;
            "add-uom": LocalJSX.AddUom & JSXBase.HTMLAttributes<HTMLAddUomElement>;
            "add-user": LocalJSX.AddUser & JSXBase.HTMLAttributes<HTMLAddUserElement>;
            "additem-grp": LocalJSX.AdditemGrp & JSXBase.HTMLAttributes<HTMLAdditemGrpElement>;
            "buis-acc": LocalJSX.BuisAcc & JSXBase.HTMLAttributes<HTMLBuisAccElement>;
            "cost-cate": LocalJSX.CostCate & JSXBase.HTMLAttributes<HTMLCostCateElement>;
            "create-camp": LocalJSX.CreateCamp & JSXBase.HTMLAttributes<HTMLCreateCampElement>;
            "create-case": LocalJSX.CreateCase & JSXBase.HTMLAttributes<HTMLCreateCaseElement>;
            "create-contact": LocalJSX.CreateContact & JSXBase.HTMLAttributes<HTMLCreateContactElement>;
            "create-cust": LocalJSX.CreateCust & JSXBase.HTMLAttributes<HTMLCreateCustElement>;
            "create-lead": LocalJSX.CreateLead & JSXBase.HTMLAttributes<HTMLCreateLeadElement>;
            "create-oppo": LocalJSX.CreateOppo & JSXBase.HTMLAttributes<HTMLCreateOppoElement>;
            "create-para": LocalJSX.CreatePara & JSXBase.HTMLAttributes<HTMLCreateParaElement>;
            "create-pote": LocalJSX.CreatePote & JSXBase.HTMLAttributes<HTMLCreatePoteElement>;
            "create-pro-cust": LocalJSX.CreateProCust & JSXBase.HTMLAttributes<HTMLCreateProCustElement>;
            "create-temp": LocalJSX.CreateTemp & JSXBase.HTMLAttributes<HTMLCreateTempElement>;
            "create-user": LocalJSX.CreateUser & JSXBase.HTMLAttributes<HTMLCreateUserElement>;
            "gen-mailer": LocalJSX.GenMailer & JSXBase.HTMLAttributes<HTMLGenMailerElement>;
            "get-account": LocalJSX.GetAccount & JSXBase.HTMLAttributes<HTMLGetAccountElement>;
            "get-activities": LocalJSX.GetActivities & JSXBase.HTMLAttributes<HTMLGetActivitiesElement>;
            "get-attendance": LocalJSX.GetAttendance & JSXBase.HTMLAttributes<HTMLGetAttendanceElement>;
            "get-budget": LocalJSX.GetBudget & JSXBase.HTMLAttributes<HTMLGetBudgetElement>;
            "get-campaign": LocalJSX.GetCampaign & JSXBase.HTMLAttributes<HTMLGetCampaignElement>;
            "get-cases": LocalJSX.GetCases & JSXBase.HTMLAttributes<HTMLGetCasesElement>;
            "get-ccentre": LocalJSX.GetCcentre & JSXBase.HTMLAttributes<HTMLGetCcentreElement>;
            "get-contact": LocalJSX.GetContact & JSXBase.HTMLAttributes<HTMLGetContactElement>;
            "get-contra": LocalJSX.GetContra & JSXBase.HTMLAttributes<HTMLGetContraElement>;
            "get-currencies": LocalJSX.GetCurrencies & JSXBase.HTMLAttributes<HTMLGetCurrenciesElement>;
            "get-daybook": LocalJSX.GetDaybook & JSXBase.HTMLAttributes<HTMLGetDaybookElement>;
            "get-emp": LocalJSX.GetEmp & JSXBase.HTMLAttributes<HTMLGetEmpElement>;
            "get-empcat": LocalJSX.GetEmpcat & JSXBase.HTMLAttributes<HTMLGetEmpcatElement>;
            "get-empgrp": LocalJSX.GetEmpgrp & JSXBase.HTMLAttributes<HTMLGetEmpgrpElement>;
            "get-godown": LocalJSX.GetGodown & JSXBase.HTMLAttributes<HTMLGetGodownElement>;
            "get-group": LocalJSX.GetGroup & JSXBase.HTMLAttributes<HTMLGetGroupElement>;
            "get-journalvoucher": LocalJSX.GetJournalvoucher & JSXBase.HTMLAttributes<HTMLGetJournalvoucherElement>;
            "get-lead": LocalJSX.GetLead & JSXBase.HTMLAttributes<HTMLGetLeadElement>;
            "get-ledger": LocalJSX.GetLedger & JSXBase.HTMLAttributes<HTMLGetLedgerElement>;
            "get-materialout": LocalJSX.GetMaterialout & JSXBase.HTMLAttributes<HTMLGetMaterialoutElement>;
            "get-opportunity": LocalJSX.GetOpportunity & JSXBase.HTMLAttributes<HTMLGetOpportunityElement>;
            "get-payheads": LocalJSX.GetPayheads & JSXBase.HTMLAttributes<HTMLGetPayheadsElement>;
            "get-payment": LocalJSX.GetPayment & JSXBase.HTMLAttributes<HTMLGetPaymentElement>;
            "get-payroll": LocalJSX.GetPayroll & JSXBase.HTMLAttributes<HTMLGetPayrollElement>;
            "get-pemail": LocalJSX.GetPemail & JSXBase.HTMLAttributes<HTMLGetPemailElement>;
            "get-plstkcat": LocalJSX.GetPlstkcat & JSXBase.HTMLAttributes<HTMLGetPlstkcatElement>;
            "get-plstkgrp": LocalJSX.GetPlstkgrp & JSXBase.HTMLAttributes<HTMLGetPlstkgrpElement>;
            "get-potential": LocalJSX.GetPotential & JSXBase.HTMLAttributes<HTMLGetPotentialElement>;
            "get-product": LocalJSX.GetProduct & JSXBase.HTMLAttributes<HTMLGetProductElement>;
            "get-purchase": LocalJSX.GetPurchase & JSXBase.HTMLAttributes<HTMLGetPurchaseElement>;
            "get-purchaseorder": LocalJSX.GetPurchaseorder & JSXBase.HTMLAttributes<HTMLGetPurchaseorderElement>;
            "get-receipt": LocalJSX.GetReceipt & JSXBase.HTMLAttributes<HTMLGetReceiptElement>;
            "get-sales": LocalJSX.GetSales & JSXBase.HTMLAttributes<HTMLGetSalesElement>;
            "get-salesorder": LocalJSX.GetSalesorder & JSXBase.HTMLAttributes<HTMLGetSalesorderElement>;
            "get-scenario": LocalJSX.GetScenario & JSXBase.HTMLAttributes<HTMLGetScenarioElement>;
            "get-singlepayslip": LocalJSX.GetSinglepayslip & JSXBase.HTMLAttributes<HTMLGetSinglepayslipElement>;
            "get-stockcate": LocalJSX.GetStockcate & JSXBase.HTMLAttributes<HTMLGetStockcateElement>;
            "get-stockgroup": LocalJSX.GetStockgroup & JSXBase.HTMLAttributes<HTMLGetStockgroupElement>;
            "get-stockitem": LocalJSX.GetStockitem & JSXBase.HTMLAttributes<HTMLGetStockitemElement>;
            "get-stockjournal": LocalJSX.GetStockjournal & JSXBase.HTMLAttributes<HTMLGetStockjournalElement>;
            "get-tariff": LocalJSX.GetTariff & JSXBase.HTMLAttributes<HTMLGetTariffElement>;
            "get-units": LocalJSX.GetUnits & JSXBase.HTMLAttributes<HTMLGetUnitsElement>;
            "get-unitw": LocalJSX.GetUnitw & JSXBase.HTMLAttributes<HTMLGetUnitwElement>;
            "get-voucher": LocalJSX.GetVoucher & JSXBase.HTMLAttributes<HTMLGetVoucherElement>;
            "imp-act": LocalJSX.ImpAct & JSXBase.HTMLAttributes<HTMLImpActElement>;
            "imp-camp": LocalJSX.ImpCamp & JSXBase.HTMLAttributes<HTMLImpCampElement>;
            "imp-case": LocalJSX.ImpCase & JSXBase.HTMLAttributes<HTMLImpCaseElement>;
            "imp-contact": LocalJSX.ImpContact & JSXBase.HTMLAttributes<HTMLImpContactElement>;
            "imp-lead": LocalJSX.ImpLead & JSXBase.HTMLAttributes<HTMLImpLeadElement>;
            "imp-oppo": LocalJSX.ImpOppo & JSXBase.HTMLAttributes<HTMLImpOppoElement>;
            "imp-pote": LocalJSX.ImpPote & JSXBase.HTMLAttributes<HTMLImpPoteElement>;
            "imp-pro-cust": LocalJSX.ImpProCust & JSXBase.HTMLAttributes<HTMLImpProCustElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-crm": LocalJSX.MyCrm & JSXBase.HTMLAttributes<HTMLMyCrmElement>;
            "my-subnav": LocalJSX.MySubnav & JSXBase.HTMLAttributes<HTMLMySubnavElement>;
            "p-login": LocalJSX.PLogin & JSXBase.HTMLAttributes<HTMLPLoginElement>;
            "schedule-call": LocalJSX.ScheduleCall & JSXBase.HTMLAttributes<HTMLScheduleCallElement>;
            "schedule-event": LocalJSX.ScheduleEvent & JSXBase.HTMLAttributes<HTMLScheduleEventElement>;
            "schedule-task": LocalJSX.ScheduleTask & JSXBase.HTMLAttributes<HTMLScheduleTaskElement>;
            "social-network": LocalJSX.SocialNetwork & JSXBase.HTMLAttributes<HTMLSocialNetworkElement>;
            "supp-lier": LocalJSX.SuppLier & JSXBase.HTMLAttributes<HTMLSuppLierElement>;
            "wel-come": LocalJSX.WelCome & JSXBase.HTMLAttributes<HTMLWelComeElement>;
        }
    }
}
